### ISSUE TITLE
[XL] Could not get Replit user ID (Chromebook)

### ISSUE THREAD

**Issue by Audomations** [lafkpages/XL-Replit#14]
**Describe the bug**
When I installed it and went to replit it didn't work. All the other features show.

**To Reproduce**
1. Go to https://replit.com/

**Expected behavior**
Get the User ID of the account.

**Screenshots**
![image](https://user-images.githubusercontent.com/96745093/219898768-3c8159e7-daf4-44da-8b83-3775d8ee7dd5.png)
![image](https://user-images.githubusercontent.com/96745093/219898797-1a084399-a86f-4879-a37a-696e7836489f.png)

**Desktop (please complete the following information):**
 - OS: Chromebook Bluebird
 - Browser: Chrome
 - Version 111.0.5563.31 (Official Build) beta (64-bit) 

**Additional context**
None

**Comment by Audomations** [comment]
I have found the actual problem with this error:

When you log out of Replit.

**Comment by lafkpages** [comment]
Yeah. When you log out of Replit, the SID you put in the popup gets invalidated and you have to change it again.
