### ISSUE TITLE
Custom Tips on Themes

### ISSUE THREAD

**Issue by DillonB07** [lafkpages/XL-Replit#19]
**Is your feature request related to a problem? Please describe.**
Can't tip custom amounts on themes
**Describe the solution you'd like**
The custom tip button from the repl cover page but on theme pages

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lafkpages** [comment]
Fixed in commit [#f2925d25623b98af9537d3c21082160277c500d0](https://github.com/lafkpages/XL-Replit/commit/f2925d25623b98af9537d3c21082160277c500d0).

**Comment by lafkpages** [comment]
Fixed in commit [#f2925d25623b98af9537d3c21082160277c500d0](https://github.com/lafkpages/XL-Replit/commit/f2925d25623b98af9537d3c21082160277c500d0).
