### ISSUE TITLE
Visiting a profile page and then going back quickly results in data on previous page.

### ISSUE THREAD

**Issue by DillonB07** [lafkpages/XL-Replit#24]
**Describe the bug**
Data being shown on the wrong page after quickly switching page.

**To Reproduce**

1. Go to home page
2. Click on  a user
3. Navigate back
4. See bug

**Expected behavior**
No data to be displayed on the home page

**Suggested Solution**
Before displaying data, check if the user is still on the correct page.

**Screenshots**

https://user-images.githubusercontent.com/83948303/231772814-2ae52b99-53cc-4099-8bcc-3dfe610499f5.mov

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6.5
- Browser: Arc Version 0.97.0 (38146) (Chromium Engine Version 112.0.5615.49)
- Version: Latest commit at creation of this issue

**Additional context**
N/A

**Comment by lafkpages** [comment]
Fixed in [#026b7bea76312389753e81933633c07c0ac885c4](https://github.com/lafkpages/XL-Replit/commit/026b7bea76312389753e81933633c07c0ac885c4).
