### ISSUE TITLE
Creating a repl redirects to `[Object%20object]`

### ISSUE THREAD

**Issue by BigKitten** [lafkpages/XL-Replit#37]
**Describe the bug**
When you create a new repl, instead of redirecting to the repl url, it redirects to `/[Object%20object]`.
**To Reproduce**

1. Enable all flags
3. Click on Create Repl
4. Choose any language
5. Click create button
6. Redirects to `/[Object%20object]` instead of repl link, however the repl is still created.

**Expected behavior**
Creating a repl should redirect to the repl link.

**Comment by lafkpages** [comment]
> Enable all flags

Do you know specifically which ones cause this? I have reason to believe it may be the "Force SSR" setting. Can you try enabling only that one?

**Comment by BigKitten** [comment]
I tested each individual flag, none of them causes this. It is likely a combination.

**Comment by lafkpages** [comment]
Can repro. Not all settings are required, as I thought, it's the "Force SSR" setting.
