### ISSUE TITLE
Extension doesn't work due to Redux store being removed

### ISSUE THREAD

**Issue by DillonB07** [lafkpages/XL-Replit#68]
**Describe the bug**
Replit has now removed `__REPLIT_REDUX_STORE__` which means that the extension does not work at all

**To Reproduce**

1. Load latest version of the extension
2. Visit Replit
3. Check extension logs

**Expected behavior**
Extension to work

**Screenshots**
<img width="705" alt="image" src="https://github.com/lafkpages/XL-Replit/assets/83948303/78f63dd6-3e82-4e92-947e-aff92692b3ad">

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: macOS Monterey 12.6.8
- Browser [e.g. chrome, safari]: Arc 1.4.1 (40966) using Chromium Engine Version 116.0.5845.96
- Version [e.g. 22]: [a40f8f7](https://github.com/lafkpages/XL-Replit/commit/a40f8f7acddc0850199fb0b9707f3c30e46898be)

**Comment by lafkpages** [comment]
Which should we use now? `__REPLIT__USER_FLAGS__.flags`, `__NEXT_DATA__.props.user.gating` or `__NEXT_DATA__.props.flagContext.flags`?

**Comment by DillonB07** [comment]
I imagine that `__REPLIT__USER_FLAGS__.flags` would be better.
